"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { rotuloMotivo } from "@/servico/rotulos";

type Report = { inicio: string; fim: string; verificadas: number; ok: number; pendentes: number; valor_em_risco: number; glosa_evitada: number; aguardando_reverificacao: number; por_codigo: Record<string, number>; por_unidade: Record<string, number>; por_convenio: Record<string, number>; frescor: { dia_ultima_carga: string | null; dias_uteis_desde_ultima_carga: number | null; defasado: boolean | null } };

export default function ReportPage() {
  const [report, setReport] = useState<Report | null>(null);
  const [inicio, setInicio] = useState(today());
  const [fim, setFim] = useState(today());
  useEffect(() => { void fetch(`/api/relatorio?inicio=${inicio}&fim=${fim}`, { cache: "no-store" }).then((response) => response.json()).then(setReport); }, [inicio, fim]);
  if (!report) return <section aria-busy="true"><h1 className="text-3xl font-semibold">Relatório</h1><p className="mt-2 text-muted-foreground">Carregando...</p></section>;
  return <section className="space-y-6"><div><h1 className="text-3xl font-semibold tracking-tight">Relatório</h1><p className="mt-2 text-muted-foreground">Resumo do período selecionado.</p></div><div className="flex flex-wrap items-end gap-3 rounded-lg border bg-card p-4"><label className="grid gap-1 text-sm"><span>De</span><input className="h-10 rounded-md border bg-background px-3" type="date" value={inicio} onChange={(event) => setInicio(event.target.value)} /></label><label className="grid gap-1 text-sm"><span>Até</span><input className="h-10 rounded-md border bg-background px-3" type="date" value={fim} onChange={(event) => setFim(event.target.value)} /></label><Button variant="outline" onClick={() => void download(`/api/relatorio/pdf?inicio=${inicio}&fim=${fim}`, `relatorio-vitalis-${inicio}-${fim}.pdf`)}>Baixar relatório PDF</Button><Button variant="ghost" onClick={() => void download(`/api/relatorio?formato=texto&inicio=${inicio}&fim=${fim}`, `relatorio-vitalis-${inicio}-${fim}.txt`)}>Baixar texto</Button></div><p className="text-sm text-muted-foreground">Período: {formatDate(report.inicio)} a {formatDate(report.fim)}</p><Freshness data={report.frescor} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Kpi title="Verificadas" value={String(report.verificadas)} /><Kpi title="OK" value={String(report.ok)} /><Kpi title="Pendentes" value={String(report.pendentes)} /><Kpi title="Em risco" value={`R$ ${report.valor_em_risco.toFixed(2).replace(".", ",")}`} /><Kpi title="Glosa evitada" value={`R$ ${report.glosa_evitada.toFixed(2).replace(".", ",")}`} /><Kpi title="Aguardando reverificação" value={String(report.aguardando_reverificacao)} /></div><div className="grid gap-6 lg:grid-cols-3"><List title="Por motivo" values={report.por_codigo} labeler={rotuloMotivo} /><List title="Por convênio" values={report.por_convenio} /><List title="Por unidade" values={report.por_unidade} /></div></section>;
}

function Kpi({ title, value }: { title: string; value: string }) { return <Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{title}</p><p className="mt-2 text-2xl font-semibold">{value}</p></CardContent></Card>; }
function List({ title, values, labeler = (value) => value }: { title: string; values: Record<string, number>; labeler?: (value: string) => string }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{Object.entries(values).map(([label, value]) => <div className="flex justify-between gap-4 text-sm" key={label}><span className="truncate">{labeler(label)}</span><strong>{value}</strong></div>)}</CardContent></Card>; }
function Freshness({ data }: { data: Report["frescor"] }) { if (!data.dia_ultima_carga) return null; const day = data.dia_ultima_carga.split("-").reverse().join("/"); return <p className={data.defasado ? "rounded-md border border-destructive/40 bg-destructive/5 p-3 text-sm" : "text-sm text-muted-foreground"}>{data.defasado ? `Atenção: os dados são de ${day}; faz ${data.dias_uteis_desde_ultima_carga} dias úteis sem carga.` : `Dados de ${day}.`}</p>; }
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function formatDate(value: string) { return value.split("-").reverse().join("/"); }
async function download(url: string, filename: string) { const response = await fetch(url); if (!response.ok) return; const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
