"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { rotuloMotivo } from "@/servico/rotulos";
import { FreshnessNotice, PageHeader } from "@/components/ui/page-header";

type Report = { inicio: string; fim: string; verificadas: number; ok: number; pendentes: number; valor_em_risco: number; glosa_evitada: number; aguardando_reverificacao: number; por_codigo: Record<string, number>; por_unidade: Record<string, number>; por_convenio: Record<string, number>; frescor: { dia_ultima_carga: string | null; dias_uteis_desde_ultima_carga: number | null; defasado: boolean | null } };

export default function ReportPage() {
  const [report, setReport] = useState<Report | null>(null);
  const [inicio, setInicio] = useState(today());
  const [fim, setFim] = useState(today());
  useEffect(() => { void fetch(`/api/relatorio?inicio=${inicio}&fim=${fim}`, { cache: "no-store" }).then((response) => response.json()).then(setReport); }, [inicio, fim]);
  if (!report) return <section aria-busy="true" className="space-y-6"><PageHeader eyebrow="Prestação de contas" title="Relatório" description="Resumo claro do período selecionado." /><div className="rounded-2xl border bg-card p-8 text-sm text-muted-foreground shadow-card">Carregando o relatório...</div></section>;
  return <section className="space-y-7"><PageHeader eyebrow="Prestação de contas" title="Relatório" description="Resumo claro do período selecionado, pronto para a reunião de terça." actions={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void download(`/api/relatorio/pdf?inicio=${inicio}&fim=${fim}`, `relatorio-vitalis-${inicio}-${fim}.pdf`)}>Baixar PDF</Button><Button variant="ghost" onClick={() => void download(`/api/relatorio?formato=texto&inicio=${inicio}&fim=${fim}`, `relatorio-vitalis-${inicio}-${fim}.txt`)}>Baixar texto</Button></div>} /><Card className="shadow-card"><CardContent className="flex flex-wrap items-end gap-4 pt-6"><div className="grid gap-2"><label className="text-sm font-medium" htmlFor="inicio">De</label><input id="inicio" className="h-10 rounded-lg border bg-background px-3 text-sm" type="date" value={inicio} onChange={(event) => setInicio(event.target.value)} /></div><div className="grid gap-2"><label className="text-sm font-medium" htmlFor="fim">Até</label><input id="fim" className="h-10 rounded-lg border bg-background px-3 text-sm" type="date" value={fim} onChange={(event) => setFim(event.target.value)} /></div><p className="pb-2 text-sm text-muted-foreground">Período: {formatDate(report.inicio)} a {formatDate(report.fim)}</p></CardContent></Card><FreshnessNotice data={report.frescor} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi title="Guias verificadas" value={String(report.verificadas)} /><Kpi title="Podem seguir" value={String(report.ok)} /><Kpi title="Precisam de ação" value={String(report.pendentes)} /><Kpi title="Valor em risco" value={`R$ ${report.valor_em_risco.toFixed(2).replace(".", ",")}`} /></div><div className="grid gap-6 lg:grid-cols-3"><List title="Por motivo" values={report.por_codigo} labeler={rotuloMotivo} /><List title="Por convênio" values={report.por_convenio} /><List title="Por unidade" values={report.por_unidade} /></div><div className="grid gap-4 sm:grid-cols-2"><Kpi title="Glosa evitada" value={`R$ ${report.glosa_evitada.toFixed(2).replace(".", ",")}`} /><Kpi title="Aguardando reverificação" value={String(report.aguardando_reverificacao)} /></div></section>;
}

function Kpi({ title, value }: { title: string; value: string }) { return <Card className="shadow-card"><CardContent className="p-5"><p className="text-sm text-muted-foreground">{title}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p></CardContent></Card>; }
function List({ title, values, labeler = (value) => value }: { title: string; values: Record<string, number>; labeler?: (value: string) => string }) { return <Card className="shadow-card"><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{Object.entries(values).sort(([, a], [, b]) => b - a).map(([label, value]) => <div className="flex justify-between gap-4 border-b border-border/60 pb-3 text-sm last:border-0 last:pb-0" key={label}><span className="truncate">{labeler(label)}</span><strong>{value}</strong></div>)}</CardContent></Card>; }
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function formatDate(value: string) { return value.split("-").reverse().join("/"); }
async function download(url: string, filename: string) { const response = await fetch(url); if (!response.ok) return; const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
