"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Freshness = { dia_ultima_carga: string | null; dias_uteis_desde_ultima_carga: number | null; defasado: boolean | null };
type Dashboard = { inicio: string; fim: string; verificadas: number; ok: number; pendentes: number; valor_em_risco: number; glosa_evitada: number; aguardando_reverificacao: number; por_codigo: Record<string, number>; por_unidade: Record<string, number>; frescor: Freshness; ultima_carga?: { createdAt: string } };

export default function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [inicio, setInicio] = useState(today());
  const [fim, setFim] = useState(today());
  useEffect(() => { const load = async () => { const response = await fetch(`/api/dashboard?inicio=${inicio}&fim=${fim}`, { cache: "no-store" }); setData(await response.json() as Dashboard); }; void load(); const timer = window.setInterval(() => void load(), 5000); return () => window.clearInterval(timer); }, [inicio, fim]);
  if (!data) return <section><h1 className="text-3xl font-semibold">Dashboard</h1><p>Carregando...</p></section>;
  return <section className="space-y-6"><div><h1 className="text-3xl font-semibold tracking-tight">Dashboard</h1><p className="mt-2 text-muted-foreground">Acompanhamento histórico da operação e do risco confirmado.</p></div><div className="flex flex-wrap items-end gap-3 rounded-lg border bg-card p-4"><label className="grid gap-1 text-sm"><span>De</span><input className="h-10 rounded-md border bg-background px-3" type="date" value={inicio} onChange={(event) => setInicio(event.target.value)} /></label><label className="grid gap-1 text-sm"><span>Até</span><input className="h-10 rounded-md border bg-background px-3" type="date" value={fim} onChange={(event) => setFim(event.target.value)} /></label><Button variant="outline" onClick={() => void download(`/api/relatorio/pdf?inicio=${inicio}&fim=${fim}`, `relatorio-vitalis-${inicio}-${fim}.pdf`)}>Baixar relatório PDF</Button></div><p className="text-sm text-muted-foreground">Período: {formatDate(data.inicio)} a {formatDate(data.fim)}</p><Freshness data={data.frescor} /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Kpi title="Verificadas" value={String(data.verificadas)} /><Kpi title="OK" value={String(data.ok)} /><Kpi title="Pendentes" value={String(data.pendentes)} /><Kpi title="Em risco" value={`R$ ${data.valor_em_risco.toFixed(2).replace(".", ",")}`} /><Kpi title="Glosa evitada" value={`R$ ${data.glosa_evitada.toFixed(2).replace(".", ",")}`} /><Kpi title="Aguardando reverificação" value={String(data.aguardando_reverificacao)} /></div><div className="grid gap-6 lg:grid-cols-2"><Chart title="Pendências por código" values={data.por_codigo} /><Chart title="Pendências por unidade" values={data.por_unidade} /></div><p className="text-sm text-muted-foreground">Última carga: {data.ultima_carga ? new Date(data.ultima_carga.createdAt).toLocaleString("pt-BR") : "nenhuma"}</p></section>;
}

function Kpi({ title, value }: { title: string; value: string }) { return <Card><CardContent className="pt-6"><p className="text-sm text-muted-foreground">{title}</p><p className="mt-2 text-2xl font-semibold">{value}</p></CardContent></Card>; }
function Freshness({ data }: { data: Freshness }) { if (!data.dia_ultima_carga) return null; const day = data.dia_ultima_carga.split("-").reverse().join("/"); return <p className={data.defasado ? "rounded-md border border-destructive/40 bg-destructive/5 p-3 text-sm" : "text-sm text-muted-foreground"}>{data.defasado ? `Atenção: os dados são de ${day}; faz ${data.dias_uteis_desde_ultima_carga} dias úteis sem carga.` : `Dados de ${day}.`}</p>; }
function Chart({ title, values }: { title: string; values: Record<string, number> }) { const max = Math.max(...Object.values(values), 1); return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-4">{Object.entries(values).map(([label, value]) => <div className="grid grid-cols-[minmax(0,1.4fr)_2fr_30px] items-center gap-2 text-sm" key={label}><span className="truncate">{label}</span><div className="h-3 overflow-hidden rounded-full bg-muted"><i className="block h-full bg-primary" style={{ width: `${(value / max) * 100}%` }} /></div><b>{value}</b></div>)}</CardContent></Card>; }
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function formatDate(value: string) { return value.split("-").reverse().join("/"); }
async function download(url: string, filename: string) { const response = await fetch(url); if (!response.ok) return; const blob = await response.blob(); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
